[package]
name = "ctl-dash"
version = "1.2.0"
edition = "2024"
license = "MPL-2.0"
description = "Displays services and logs and allows you to enable/disable/start/stop/restart every service."
repository = "https://github.com/nikelaz/ctl-dash"

[dependencies]
futures-util = "0.3.34"
i18n-embed = { version = "0.16.0", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10.1"
open = "5.4.2"
rust-embed = "8.12.0"
tokio = { version = "1.53.1", features = ["full"] }
zbus = { version = "5.19", default-features = false, features = ["tokio"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
rev = "c003a58fff660f5c55ebfb54a5908722fa7d1d6e"
features = [
    "a11y",
    "about",
    "dbus-config",
    "multi-window",
    "single-instance",
    "tokio",
    "winit",
    "wayland",
    "wgpu",
]
